### ISSUE TITLE
[Bug]: Browser testing doesn't work for domain based routing

### ISSUE THREAD

**Issue by chrispage1** [pestphp/pest#1443]
### What Happened

Hi,

I installed PestPHP 4 for its browser testing but my project uses domain based routing.

I can completely see how this presents an issue and why this is problematic, I considered overriding the domain to the temporary server URL but I don't know it until its happened as the port is dynamic.

Is there a workaround for this?

### How to Reproduce

Pull down the test project and run the tests

### Sample Repository

https://github.com/chrispage1/pest4-testing

### Pest Version

4.0.0

### PHP Version

8.4.11

### Operation System

macOS

**Comment by nunomaduro** [comment]
currently having fun at laravel live dk, can you try to come up with a pull request for that? check the laravel http server class, and see if you can "by pass" that check.

**Comment by chrispage1** [comment]
> currently having fun at laravel live dk, can you try to come up with a pull request for that? check the laravel http server class, and see if you can "by pass" that check.

Will do Nuno 🫡 Hope you're enjoying Laravel Live!

**Comment by chrispage1** [comment]
Hey @nunomaduro - I've raised a PR in the Laravel project as this seems like a logical place to do it!

**Comment by ju5t** [comment]
I found this issue after creating a [PR](https://github.com/pestphp/pest-plugin-browser/pull/128) in the browser plugin which overrides the host header as @nunomaduro mentioned before. I don't want to boast my PR here but thought it could help in deciding what approach would suit this issue best.

**Comment by chrispage1** [comment]
> I found this issue after creating a [PR](https://github.com/pestphp/pest-plugin-browser/pull/128) in the browser plugin which overrides the host header as [@nunomaduro](https://github.com/nunomaduro) mentioned before. I don't want to boast my PR here but thought it could help in deciding what approach would suit this issue best.

Ah I do like you're implementation here! It does make sense that it's perhaps better to specify the hostname rather than ignore altogether as that is then another level of testing.

**Comment by calebdw** [comment]
We also have domain based routing (several domains) in a monorepo. In our existing playwright tests we had fixtures for each domain that would set things like the base url for all requests.

**Comment by okaufmann** [comment]
It was added https://github.com/pestphp/pest-plugin-browser/commit/d917f1b30107e3608833d18794749dd6995f0d9d and removed again https://github.com/pestphp/pest-plugin-browser/commit/45e762f14cc20072d85c83cc2513cbeac6fe6584. What is the current state of supporting multi domain projects @nunomaduro ?

**Comment by pindab0ter** [comment]
> We also have domain based routing (several domains) in a monorepo. In our existing playwright tests we had fixtures for each domain that would set things like the base url for all requests.

Do you reckon there is a way to do this with Pest 4, even as a workaround? I imagine navigating between different subdomains would not work? Could you give us an idea of what those fixtures looked like?

**Comment by ju5t** [comment]
I don't think there is a workaround at the moment. The way this plugin is structured means you don't have access to the Symfony request that gets passed to the HTTP server they boot up. And you need that to set a `Host` header. 

My PR did all that, but it got removed later without any feedback, which is a shame, but it is what it is.

**Comment by abrardev99** [comment]
> We also have domain based routing (several domains) in a monorepo. In our existing playwright tests we had fixtures for each domain that would set things like the base url for all requests.

Can you please share or give an idea how to set up fixtures like these?

**Comment by ju5t** [comment]
@valerius21 it is what it is, in the end it's @nunomaduro's package, if he doesn't want to support it that's his decision. We can always fork it if we disagree.

I would've loved an explanation for my PR being undone so it can be improved, but again, thats up to Nuno.

**Comment by nunomaduro** [comment]
fixed: https://nunomaduro.com/posts/pest-with-host-browser-testing-subdomains-laravel

**Comment by pindab0ter** [comment]
Thank you so much, @nunomaduro!

**Comment by chrispage1** [comment]
Nice work @nunomaduro - thank you!!

**Comment by moisish** [comment]
I still have issues when using Valet eg hosts are .test. Anyone else having issues working with Browser testing and subdomains and valet?
